### ISSUE TITLE
how to run it 

### ISSUE THREAD

**Issue by dllen** [chriskapp/amun#1]
when i run it occer

Internal Server Error

Page not found in D:\phpcode\amun\library\Amun\Loader\LocationFinder.php on line 192
#0 D:\phpcode\amun\library\Amun\Loader\LocationFinder.php(71): Amun\Loader\LocationFinder->resolveApplication('')
#1 D:\phpcode\amun\vendor\psx\psx\library\PSX\Loader.php(200): Amun\Loader\LocationFinder->resolve('')
#2 D:\phpcode\amun\vendor\psx\psx\library\PSX\Loader.php(64): PSX\Loader->resolvePath('', Object(PSX\Http\Request))
#3 D:\phpcode\amun\vendor\psx\psx\library\PSX\Dispatch.php(57): PSX\Loader->load('', Object(PSX\Http\Request))
#4 D:\phpcode\amun\public\index.php(31): PSX\Dispatch->route(Object(PSX\Http\Request))
#5 {main}

**Comment by chriskapp** [comment]
Hi, which version have you tried to install? Try the following command to install the latest stable version through composer

```
composer create-project amun/amun .
```
